server:
  port:8089
spring:
  application:
    name: rating_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopee_rating
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  liquibase:
    enabled: true