name: inventory service ci

on:
  push:
    branches: ["main"]
    paths:
      - "inventory/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/inventory-ci.yaml"

  pull_request:
    branches: ["main"]
    paths:
      - "inventory/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/inventory-ci.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven build command
        run: mvn clean install -DskipTests -pl inventory -am
      - name: Run maven test
        run: mvn test -pl inventory -am
#      - name: Unit test result
#        uses: dorny/test-reporter@v1
#        with:
#          name: Inventory service unit test results
#          path: "inventory/**/surefire-reports/*.xml"
#          reporter: java-junit
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v3
        with:
          context: ./inventory
          push: true
          tags: ghcr.io/nguyen-nhat/shopee-inventory:latest
