name: tax service ci

on:
  push:
    branches: ["main"]
    paths:
      - "tax/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/tax-ci.yaml"

  pull_request:
    branches: ["main"]
    paths:
      - "tax/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/tax-ci.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions
      - name: Run maven build command
        run: mvn clean install -DskipTests -pl tax -am
      - name: Run maven test
        run: mvn test -pl tax -am
#      - name: Unit test result
#        uses: dorny/test-reporter@v1
#        with:
#          name: Tax service unit test results
#          path: "tax/**/surefire-reports/*.xml"
#          reporter: java-junit
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker images
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v3
        with:
          context: ./tax
          push: true
          tags: ghcr.io/nguyen-nhat/shopee-tax:latest
